###
# @name DataverseInstanceInformation
GET {{dataverse_instanceUrl}}/api/data/v9.2
  /RetrieveCurrentOrganization(AccessType=@AccessType)
  ?@AccessType=Microsoft.Dynamics.CRM.EndpointAccessType'Default'
Authorization: oauth2 {{dataverse_grantType}} dataverse
OData-Version: 4.01
OData-MaxVersion: 4.01
Prefer: odata.include-annotations=*

?? status == 200
?? body Detail exists

###
# @name AcquireAccessTokenForManagedIdentity
{{
  request.options.json = {
    Scopes: [`${dataverse_instanceUrl}/.default`],
    Application: {
      "@id": "/managedidentities(1304a7e4-ed28-f011-8c4d-7c1e5226ec1f)",
    },
  };
}}
POST {{dataverse_instanceUrl}}/api/data/v9.2
  /pwrplatf_AcquireAccessTokenForApplication
Authorization: oauth2 code dataverse
OData-Version: 4.01
OData-MaxVersion: 4.01
Prefer: odata.include-annotations=*

?? status == 200
?? body AccessToken exists

###
# @name AcquireAccessTokenForApplication
@dataverse_applicationCredentials_keyVaultUri = {{$input-askonce Key Vault URI for Application Credentials}}
@dataverse_applicationCredentials_secretName = {{$input-askonce Key Vault Secret Name for Application Credentials}}
{{
  request.options.json = {
    Scopes: [`${dataverse_instanceUrl}/.default`],
    ApplicationEntity: {
      "@type": "Microsoft.Dynamics.CRM.managedidentity",
      name: "Fredriksperiment",
      // tenantid: "<tenant-id>", // Not required
      applicationid: "6a7576eb-e377-4b0e-995b-f79de45e8d59",
    },
    ClientCredentialsSourceEntity: {
      "@type": "Microsoft.Dynamics.CRM.keyvaultreference",
      keytype: 0,
      keyvaulturi: dataverse_applicationCredentials_keyVaultUri,
      keyname: dataverse_applicationCredentials_secretName,
    }
  };
}}
POST {{dataverse_instanceUrl}}/api/data/v9.2
  /pwrplatf_AcquireAccessTokenForApplication
Authorization: oauth2 code dataverse
OData-Version: 4.01
OData-MaxVersion: 4.01
Prefer: odata.include-annotations=*

?? status == 200
?? body AccessToken exists

###
# @name AcquireAccessTokenForAgentBlueprint
@dataverse_blueprintCredentials_keyVaultUri = {{$input-askonce Key Vault URI for Agent Blueprint Credentials}}
@dataverse_blueprintCredentials_secretName = {{$input-askonce Key Vault Secret Name for Agent Blueprint Credentials}}
{{
  request.options.json = {
    Scopes: ["api://AzureADTokenExchange/.default"],
    ApplicationEntity: {
      "@type": "Microsoft.Dynamics.CRM.managedidentity",
      name: "FredrikHr Power Platform Managed Identity Agent Blueprint",
      applicationid: "e5a2f785-3a15-4e6b-91f9-2124c2cd26ec",
    },
    ClientCredentialsSourceEntity: {
      "@type": "Microsoft.Dynamics.CRM.keyvaultreference",
      keytype: 0,
      keyvaulturi: dataverse_blueprintCredentials_keyVaultUri,
      keyname: dataverse_blueprintCredentials_secretName,
    },
    FmiPath: "5200af47-b7ad-4580-af2f-42167adbfcc2"
  };
}}
POST {{dataverse_instanceUrl}}/api/data/v9.2
  /pwrplatf_AcquireAccessTokenForApplication
Authorization: oauth2 code dataverse
OData-Version: 4.01
OData-MaxVersion: 4.01
Prefer: odata.include-annotations=*

?? status == 200
?? body AccessToken exists

###
# @name AcquireAccessTokenForAgentIdentity
# @ref AcquireAccessTokenForAgentBlueprint
{{
  request.options.form = {
    grant_type: "client_credentials",
    client_id: "5200af47-b7ad-4580-af2f-42167adbfcc2",
    client_assertion_type: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
    client_assertion: AcquireAccessTokenForAgentBlueprint.AccessToken,
    scope: `${dataverse_instanceUrl}/.default`,
  };
}}
POST {{dataverse_tokenEndpoint}}

?? status == 200
?? body access_token exists
