#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FredrikHr.PowerPlatformCustomDelegation.Entities
{
	
	
	/// <summary>
	/// Microsoft Entra ID Secure Token Service Instance
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msal_azurecloudinstance
	{
		
		/// <summary>
		/// Automatically inferred from current environment
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Automatic = 0,
		
		/// <summary>
		/// Microsoft Azure public cloud. Maps to https://login.microsoftonline.com
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Public = 1,
		
		/// <summary>
		/// Microsoft Azure China cloud. Maps to https://login.chinacloudapi.cn
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		China = 2,
		
		/// <summary>
		/// Microsoft Azure German cloud ("Black Forest"). Maps to https://login.microsoftonline.de
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Germany = 3,
		
		/// <summary>
		/// US Government cloud. Maps to https://login.microsoftonline.us
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UsGovernment = 4,
	}
}
#pragma warning restore CS1591
